language: python
python:
  - "3.8"


services:
  - docker
  - postgresql

before_script:
  - pip install docker-compose
  - psql -c 'create database test;' -U postgres -p 5434


script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  - python manage.py migrate
