language: python
python:
  - "3.8"


services:
  - docker
  - postgresql

before_script:
  - pip install docker-compose
  - psql -c 'create database ysdb;' -U postgres -p 5432


script:
  - docker-compose up app sh -c "python manage.py migrate && python manage.py test && flake8"
