# Generated by Django 3.2.8 on 2021-10-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USERS'},
        ),
    ]
