# Generated by Django 3.2.8 on 2021-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211103_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile', verbose_name='Profile Image'),
        ),
    ]
