# Generated by Django 3.2.9 on 2021-11-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
