# Generated by Django 3.2.9 on 2021-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='DELETED_AT')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Name')),
                ('cover_image', models.ImageField(blank=True, upload_to='food_images', verbose_name='Cover Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
