# Generated by Django 3.2.9 on 2021-11-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
    ]
