# Generated by Django 3.2.9 on 2021-11-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Item Count'),
        ),
    ]
