# Generated by Django 3.2.9 on 2021-11-24 22:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='item_count',
        ),
    ]
