# Generated by Django 3.2.9 on 2021-11-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211120_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('completed', 'Completed')], db_index=True, default='created', max_length=20, verbose_name='Status'),
        ),
    ]
