# Generated by Django 3.2.9 on 2021-11-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='total',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food', to='order.order', verbose_name='Order'),
        ),
    ]
