# Generated by Django 3.2.9 on 2021-11-21 18:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211121_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6, verbose_name='Price'),
        ),
    ]
