# Generated by Django 3.2.9 on 2021-11-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderfood_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfood',
            old_name='Price',
            new_name='price',
        ),
    ]
